// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVTkYJlXHb37rEoUJfU324bTTDljPcIns',
    appId: '1:257618688270:web:239d96549c7002de307f5f',
    messagingSenderId: '257618688270',
    projectId: 'design-thinking-project-df689',
    authDomain: 'design-thinking-project-df689.firebaseapp.com',
    storageBucket: 'design-thinking-project-df689.firebasestorage.app',
    measurementId: 'G-2FV2DD1L9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKkgOhu0pBPUa79puBRxNAivTruG009o',
    appId: '1:257618688270:android:b08634cfb9a6465a307f5f',
    messagingSenderId: '257618688270',
    projectId: 'design-thinking-project-df689',
    storageBucket: 'design-thinking-project-df689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhYdxwhLDTfyjdj-i8RIjPLj0HWWYVCvk',
    appId: '1:257618688270:ios:02b524785a2eaba7307f5f',
    messagingSenderId: '257618688270',
    projectId: 'design-thinking-project-df689',
    storageBucket: 'design-thinking-project-df689.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhYdxwhLDTfyjdj-i8RIjPLj0HWWYVCvk',
    appId: '1:257618688270:ios:02b524785a2eaba7307f5f',
    messagingSenderId: '257618688270',
    projectId: 'design-thinking-project-df689',
    storageBucket: 'design-thinking-project-df689.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVTkYJlXHb37rEoUJfU324bTTDljPcIns',
    appId: '1:257618688270:web:5b7b088812400000307f5f',
    messagingSenderId: '257618688270',
    projectId: 'design-thinking-project-df689',
    authDomain: 'design-thinking-project-df689.firebaseapp.com',
    storageBucket: 'design-thinking-project-df689.firebasestorage.app',
    measurementId: 'G-WHNDQQTVC1',
  );
}
